# Generated by Django 5.2.17 on 2026-08-25 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('records_found', models.PositiveIntegerField(default=0)),
                ('imported', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('title_english', models.CharField(max_length=255)),
                ('title_arabic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title_english'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='unique_course_code_when_present')],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration_open', 'Registration open'), ('registration_closed', 'Registration closed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('public_registration_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sessions', to='portal.camp')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='portal.course')),
            ],
            options={
                'ordering': ['-start_date', 'course__title_english'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_role', models.CharField(choices=[('lead', 'Lead Instructor'), ('assistant', 'Assistant Instructor'), ('observer', 'Observer'), ('coordinator', 'Coordinator')], default='lead', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='portal.coursesession')),
            ],
            options={
                'ordering': ['session', 'assignment_role', 'instructor'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('eid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('name_english', models.CharField(max_length=255)),
                ('name_arabic', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='portal.instructor')),
                ('roles', models.ManyToManyField(blank=True, related_name='instructors', to='portal.instructorrole')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='portal.team')),
            ],
            options={
                'ordering': ['name_english'],
            },
        ),
        migrations.AddField(
            model_name='coursesession',
            name='instructors',
            field=models.ManyToManyField(related_name='course_sessions', through='portal.CourseInstructor', to='portal.instructor'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='portal.instructor'),
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_sheet', models.CharField(blank=True, max_length=150)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('invalid_id', 'Invalid ID'), ('identity_conflict', 'Identity conflict'), ('date_conflict', 'Date conflict'), ('duplicate', 'Possible duplicate'), ('source_mismatch', 'Source mismatch'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('accepted_as_is', 'Accepted as-is')], default='open', max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('original_value', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('decision_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_data_issues', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='portal.sourcefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('eid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('name_english', models.CharField(blank=True, max_length=255)),
                ('name_arabic', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('identity_status', models.CharField(choices=[('verified', 'Verified'), ('review', 'Needs review'), ('invalid_id', 'Invalid ID')], default='review', max_length=20)),
                ('is_hp', models.BooleanField(default=False)),
                ('is_ttt', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name_english', 'name_arabic', 'eid'],
                'indexes': [models.Index(fields=['name_english'], name='portal_stud_name_en_099ff2_idx'), models.Index(fields=['name_arabic'], name='portal_stud_name_ar_2d33f8_idx'), models.Index(fields=['email'], name='portal_stud_email_2435df_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('eid__isnull', False), models.Q(('eid', ''), _negated=True)), fields=('eid',), name='unique_student_eid_when_present')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_name_english', models.CharField(blank=True, max_length=255)),
                ('submitted_name_arabic', models.CharField(blank=True, max_length=255)),
                ('eid_raw', models.CharField(blank=True, max_length=100)),
                ('eid_normalized', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email_raw', models.CharField(blank=True, max_length=255)),
                ('phone_raw', models.CharField(blank=True, max_length=100)),
                ('training_date_raw', models.CharField(blank=True, max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs review')], default='pending', max_length=20)),
                ('source_sheet', models.CharField(blank=True, max_length=150)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('requested_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='portal.coursesession')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='portal.sourcefile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='portal.student')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attendance', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('partial', 'Partial'), ('not_recorded', 'Not recorded')], default='pending', max_length=20)),
                ('assessment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('withdrawn', 'Withdrawn'), ('not_assessed', 'Not assessed')], default='pending', max_length=20)),
                ('record_status', models.CharField(choices=[('registered', 'Registered'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('is_hp', models.BooleanField(default=False)),
                ('is_ttt', models.BooleanField(default=False)),
                ('duplicate_flag', models.BooleanField(db_index=True, default=False)),
                ('duplicate_notes', models.TextField(blank=True)),
                ('source_sheet', models.CharField(blank=True, max_length=150)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='portal.coursesession')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='portal.sourcefile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='portal.student')),
            ],
            options={
                'ordering': ['-session__start_date', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['status', 'start_date'], name='portal_cour_status_3eb1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['camp', 'start_date'], name='portal_cour_camp_id_f7fdf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('session', 'instructor', 'assignment_role'), name='unique_session_instructor_role'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status', 'submitted_at'], name='portal_regi_status_30bead_idx'),
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.UniqueConstraint(condition=models.Q(('eid__isnull', False), models.Q(('eid', ''), _negated=True)), fields=('eid',), name='unique_instructor_eid_when_present'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['attendance', 'result'], name='portal_trai_attenda_4c459a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['record_status'], name='portal_trai_record__a6bf48_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['is_hp', 'is_ttt'], name='portal_trai_is_hp_ada8e9_idx'),
        ),
    ]

