# Generated by Django 5.2.17 on 2026-08-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_record_id', models.UUIDField(editable=False, unique=True)),
                ('worksheet_name', models.CharField(max_length=150)),
                ('source_row_number', models.PositiveIntegerField()),
                ('record_type', models.CharField(db_index=True, max_length=80)),
                ('raw_payload', models.JSONField(default=dict)),
                ('derived_search_values', models.JSONField(blank=True, default=dict)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('import_status', models.CharField(choices=[('staged', 'Staged'), ('needs_review', 'Needs review'), ('converted', 'Converted'), ('ignored', 'Ignored after review')], db_index=True, default='staged', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('linked_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.registration')),
                ('linked_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.coursesession')),
                ('linked_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.student')),
                ('linked_training_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.trainingrecord')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='portal.sourcefile')),
            ],
            options={
                'ordering': ['source_file', 'worksheet_name', 'source_row_number'],
                'indexes': [models.Index(fields=['record_type', 'import_status'], name='portal_sour_record__90e09b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_file', 'worksheet_name', 'source_row_number', 'record_type'), name='unique_historical_source_record')],
            },
        ),
    ]

