# Generated by Django 5.2.17 on 2026-08-25 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_sourcerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdentityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.UUIDField(editable=False, unique=True)),
                ('normalized_eid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('proposal_status', models.CharField(choices=[('single_valid_id', 'Single valid ID'), ('exact_id_match', 'Exact-ID match'), ('review_required', 'Review required'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('proposed_name_english', models.CharField(blank=True, max_length=255)),
                ('proposed_name_arabic', models.CharField(blank=True, max_length=255)),
                ('proposed_email', models.CharField(blank=True, max_length=255)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('source_types', models.JSONField(blank=True, default=dict)),
                ('english_name_values', models.JSONField(blank=True, default=list)),
                ('arabic_name_values', models.JSONField(blank=True, default=list)),
                ('email_values', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notes', models.TextField(blank=True)),
                ('approved_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_proposal', to='portal.student')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_proposals', to=settings.AUTH_USER_MODEL)),
                ('source_records', models.ManyToManyField(blank=True, related_name='student_identity_proposals', to='portal.sourcerecord')),
            ],
            options={
                'ordering': ['proposal_status', 'normalized_eid'],
                'indexes': [models.Index(fields=['proposal_status'], name='portal_stud_proposa_62c145_idx')],
            },
        ),
    ]

