# Generated by Django 5.2.17 on 2026-08-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_studentidentityproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerecord',
            name='linked_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.camp'),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='linked_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.course'),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='linked_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evidence', to='portal.instructor'),
        ),
    ]

