# Generated by Django 5.2.17 on 2026-08-25 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_sourcerecord_linked_camp_sourcerecord_linked_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSessionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.UUIDField(editable=False, unique=True)),
                ('proposal_source', models.CharField(choices=[('registration_group', 'Registration group'), ('ttt_evidence_group', 'TTT evidence group'), ('specialized_result_and_attendance', 'Specialized result and attendance'), ('camp_operational_summary', 'Camp operational summary')], db_index=True, max_length=50)),
                ('proposal_status', models.CharField(choices=[('pending', 'Pending review'), ('review_required', 'Review required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('camp_values', models.JSONField(blank=True, default=list)),
                ('unit_values', models.JSONField(blank=True, default=list)),
                ('instructor_values', models.JSONField(blank=True, default=list)),
                ('evidence_records', models.PositiveIntegerField(default=0)),
                ('student_id_values', models.PositiveIntegerField(default=0)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notes', models.TextField(blank=True)),
                ('approved_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='portal.coursesession')),
                ('proposed_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_proposals', to='portal.camp')),
                ('proposed_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_proposals', to='portal.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_course_proposals', to=settings.AUTH_USER_MODEL)),
                ('source_records', models.ManyToManyField(blank=True, related_name='course_session_proposals', to='portal.sourcerecord')),
            ],
            options={
                'ordering': ['proposal_status', '-start_date', 'proposal_source'],
                'indexes': [models.Index(fields=['proposal_source', 'proposal_status'], name='portal_cour_proposa_fa6f3a_idx'), models.Index(fields=['start_date', 'end_date'], name='portal_cour_start_d_8144cc_idx')],
            },
        ),
    ]

