# Generated by Django 5.2.17 on 2026-08-26 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_activitylog_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAliasProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.UUIDField(editable=False, unique=True)),
                ('alias_type', models.CharField(choices=[('camp', 'Camp'), ('instructor', 'Instructor')], db_index=True, max_length=20)),
                ('source_value', models.TextField()),
                ('normalized_source', models.TextField(db_index=True)),
                ('similarity_score', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('match_method', models.CharField(blank=True, max_length=80)),
                ('proposal_status', models.CharField(choices=[('proposed', 'High-confidence proposal'), ('review_required', 'Review required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=30)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notes', models.TextField(blank=True)),
                ('proposed_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_proposals', to='portal.camp')),
                ('proposed_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_proposals', to='portal.instructor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entity_aliases', to=settings.AUTH_USER_MODEL)),
                ('source_records', models.ManyToManyField(blank=True, related_name='entity_alias_proposals', to='portal.sourcerecord')),
            ],
            options={
                'ordering': ['alias_type', 'proposal_status', 'source_value'],
                'indexes': [models.Index(fields=['alias_type', 'proposal_status'], name='portal_enti_alias_t_7b8e18_idx')],
                'constraints': [models.UniqueConstraint(fields=('alias_type', 'source_value'), name='unique_entity_alias_source_value')],
            },
        ),
    ]

