# Generated by Django 5.2.17 on 2026-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_entityaliasproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='submitted_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]

