# Generated by Django 5.2.17 on 2026-08-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_registration_submitted_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='day1_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='day2_attended',
            field=models.BooleanField(default=False),
        ),
    ]

