# Generated by Django 5.2.17 on 2026-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_registration_day1_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='assessment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('absent', 'Absent'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
    ]

