# Generated by Django 5.2.17 on 2026-08-27 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_stampedlistarchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseStudentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('hp', 'HP (High Performance)'), ('ttt', 'TTT')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('nominated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_tag_nominations_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_tag_nominations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tag_nominations', to='portal.coursesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tag_nominations', to='portal.student')),
                ('training_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_nominations', to='portal.trainingrecord')),
            ],
            options={
                'ordering': ['-nominated_at', 'student__name_english', 'tag_type'],
                'constraints': [models.UniqueConstraint(fields=('session', 'student', 'tag_type'), name='unique_course_student_tag_type')],
            },
        ),
    ]

