# Generated by Django 5.2.17 on 2026-08-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_instructor_user_coursestudenttag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStudentTag',
        ),
    ]

